[[guide-push-notifications-concepts]]
[role="chunk-page chunk-toc"]
=== Concepts

--
--

[[guide-push-notifications-concepts-introduction]]
==== Introduction

Push Notifications are a great way to keep your players engaged and
informed about your games. You can reach your entire user base quickly
and effectively. This guide will help you through the setup process and
the general usage of Scoreflex to send push notifications.

[[guide-push-notifications-concepts-why-use-scoreflex-for-your-push-notifications]]
==== Why use Scoreflex for your push notifications?

Adding push notifications to your games can be a complicated and tedious
task:

* You need to have your own backends to store devices' identifiers and
  players' information.
* You need to have your own backends to communicate with remote servers
  to send push notifications.
* You probably need to have some kind of queue logic and properly handle
  errors and retries to make sure your notifications are sent and not lost.
* You want to avoid sending too many push notifications to your players
  and therefore you need to implement some kind of throttling logic not to
  bother your players.
* You have to manage errors in order to clean up your devices'
  identifiers database.
* You have to be able to store and search players' information to target your
  audience properly in order to communicate to only a subset of your players.
* You need to implement and run computing intensive tasks in order to send
  advanced push notification related to complex events.
  For example a player's friend has just beaten his high score on level 2.
* You probably need some statistics about how many push notifications
  you have sent, how many push notifications were properly delivered and so on.
* The list goes on...

Scoreflex aims to solve all this for you so you can focus on your game.

[[guide-push-notifications-concepts-types-of-push-notifications]]
==== Types of push notifications

In Scoreflex, there are three different types of push notifications:

. Automatic notifications. These notifications are automatically
  managed and sent by Scoreflex to your players to alert them about
  interesting events about your game like:
  *  One of your friends has joined the game
  *  One of your friends has just beaten your high score on a level
  *  A player has invited you to a challenge
  *  A challenge you were part of has ended
  *  It's your turn to play in a turn-based challenge
  *  You have reached a new level of expertise
  *  More to come...
. Developer to player notifications. As a developer you can decide to
  send push notifications to all your players or to a targeted portion of
  your players. For example, this can be useful to inform them about some
  cool news about your game or maybe to let them know that you have just
  released a new game. You can use advanced filters to target all
  your users playing game A that are men between 20 and 30 years old
  and living in California.
. Players to players notifications. You can use Scoreflex API from
  your game to send push notifications to other players.

[[guide-push-notifications-concepts-basic-steps]]
==== Basic steps

Here are the basic steps regarding how to handle push notifications:

. Configure your game certificates using the web developer dashboard
  or the management REST API.
. Register a device token when your game is launched. The term “device
  token” in Scoreflex designates the identifier that is used to send a
  push notification to a particular device on various platforms. For
  example in the Android world, the Scoreflex device token is the
  registration id.
. Add code to handle received push notifications in your client.

[[guide-push-notifications-concepts-channels]]
==== Channels

A simple way to start sending notifications to a targeted audience is
using channels. This allows you to use a publisher-subscriber model for
sending pushes. Devices start by subscribing to one or more channels,
and notifications can later be sent to these subscribers.

[[guide-push-notifications-concepts-multiple-devices]]
==== Multiple devices

When a player has multiple devices registered for a game, you can choose
to send a push notification only to the latest device used for this game
or to all their devices. By default, the push notification will be sent to
all devices.

[[guide-push-notifications-concepts-platforms]]
==== Platforms

Scoreflex currently supports push notifications on iOS and Android.
Please refer to the relevant iOS and Android guides for more
information.

[[guide-push-notifications-concepts-throttling-and-spam-management]]
==== Throttling and spam management

It can be counter productive to send too many push notifications to your
players especially if they didn't react to previously sent
notifications. Thus, an automatic Scoreflex notification to a player is
not sent if another automatic notification has been sent during the last
4 hours and the player has not act in the game ever since. For testing
purpose, this constraint does not apply in sandbox. This constraint does
not apply to developer to players notifications or to players to players
notifications as you, as the game's developer, have complete control to
how you reach your audience.

If you ban a player from one of your game, some of his actions that
would normally lead to the sending of a push notification (challenge
invitation, player has beaten your highscore, ...) won't.
