[[guide-push-notifications-interact]]
[role="chunk-page chunk-toc"]
=== Interact

[[guide-push-notifications-interact-managing-certificates]]
==== Managing certificates

You can use your web dashboard the Management REST API to manage your
game certificates for push notifications.

NOTE: Certificates are isolated between sandbox and production. On iOS,
you have to use your development certificate on sandbox which is
different from your production certificate.

[[guide-push-notifications-interact-managing-certificates-updating-certificate]]
===== Updating certificate

[source,sh]
----
$> curl -s -XPOST \
   'https://sandbox.api.scoreflex.com/v1/management/games/<GAME_ID>/certificates/platforms/iOS?accessToken=<DEVELOPER_ACCESS_TOKEN>' \
   --data-binary @<CERTIFICATE_PATH>
----

[source,js]
----
{"success":true}
----

[[guide-push-notifications-interact-managing-certificates-getting-certificate]]
===== Getting certificate

[source,sh]
----
$> curl -XGET \
   'https://sandbox.api.scoreflex.com/v1/management/games/<GAME_ID>/certificates/platforms/iOS?accessToken=<DEVELOPER_ACCESS_TOKEN>'
----


[source,js]
----
<CERTIFICATE_DATA>
----

[[guide-push-notifications-interact-managing-certificates-deleting-certificate]]
===== Deleting certificate

[source,sh]
----
$> curl -XDELETE \
   'https://sandbox.api.scoreflex.com/v1/management/games/<GAME_ID>/certificates/platforms/iOS?accessToken=<DEVELOPER_ACCESS_TOKEN>'
----


[source,js]
----
{"success":true}
----

[[guide-push-notifications-interact-managing-device-tokens]]
==== Managing device tokens

Before sending push notification to a device you have to register the
corresponding device token to Scoreflex from your game code.

[[guide-push-notifications-interact-managing-device-tokens-registering-a-device-token]]
===== Registering a device token

[source,sh]
----
$> curl -XPOST \
   'https://sandbox.api.scoreflex.com/v1/notifications/deviceTokens?token=[https://sandbox.api.scoreflex.com/v1/notifications/deviceTokens?token=]<DEVICE_TOKEN>&accessToken=<ACCESS_TOKEN>'
----


[source,js]
----
{"success":true}
----

[[guide-push-notifications-interact-managing-device-tokens-unregistering-current-device-token]]
===== Unregistering current device token

[source,sh]
----
$> curl \
   -XDELETE'https://sandbox.api.scoreflex.com/v1/notifications/deviceTokens?token=[https://sandbox.api.scoreflex.com/v1/notifications/deviceTokens?]accessToken=<ACCESS_TOKEN>'
----


[source,js]
----
{"success":true}
----

[[guide-push-notifications-interact-managing-channels-subscriptions]]
==== Managing channels subscriptions

[[guide-push-notifications-interact-managing-channels-subscriptions-subscribing-to-new-channels]]
===== Subscribing to new channels

Valid channels are of the form +[0-9a-zA-Z_]{1,20}+. You can subscribe to
channels when registering a device token or by explicitly calling:

[source,sh]
----
$> curl -XPOST \
   'https://sandbox.api.scoreflex.com/v1/notifications/deviceTokens?token=[https://sandbox.api.scoreflex.com/v1/notifications/deviceTokens/subscriptions/channel1,channel2?]accessToken=<ACCESS_TOKEN>'
----


[source,js]
----
{"success":true}
----

[[guide-push-notifications-interact-managing-channels-subscriptions-getting-all-subscribed-channels]]
===== Getting all subscribed channels

[source,sh]
----
$> curl -XGET \
   'https://sandbox.api.scoreflex.com/v1/notifications/deviceTokens?token=[https://sandbox.api.scoreflex.com/v1/notifications/deviceTokens/subscriptions?]accessToken=<ACCESS_TOKEN>&pretty=true'
----


[source,js]
----
[
 "channel1",
 "channel2"
]
----

[[guide-push-notifications-interact-managing-channels-subscriptions-unsubscribing-from-some-channels]]
===== Unsubscribing from some channels

[source,sh]
----
$> curl -XDELETE \
   'https://sandbox.api.scoreflex.com/v1/notifications/deviceTokens?token=[https://sandbox.api.scoreflex.com/v1/notifications/deviceTokens/subscriptions/channel1?]accessToken=<ACCESS_TOKEN>'
----


[source,js]
----
{"success":true}
----

[[guide-push-notifications-interact-managing-channels-subscriptions-unsubscribing-from-all-channels]]
===== Unsubscribing from all channels

[source,sh]
----
$> curl -XDELETE \
   'https://sandbox.api.scoreflex.com/v1/notifications/deviceTokens?token=[https://sandbox.api.scoreflex.com/v1/notifications/deviceTokens/subscriptions?]accessToken=<ACCESS_TOKEN>'
----


[source,js]
----
{"success":true}
----

[[guide-push-notifications-interact-sending-developer-to-players-notifications]]
==== Sending developer to players notifications

You can use your web dashboard or the Management REST API to send push
notifications to your players.

More coming soon on this topic.

[[guide-push-notifications-interact-sending-players-to-players-notifications]]
==== Sending players to players notifications

You can use the REST API to send push notifications from your games.

More coming soon on this topic.
