[[guide-push-notifications-reference]]
[role="chunk-page chunk-toc"]
=== [title-badge-push-notifications]#Reference#

--
--

[[guide-push-notifications-reference-push-notification-message-attributes]]
==== Push notification message attributes

A typical iOS push notification message has the following format:

[source,js]
----
{
  "aps":
  {
    "alert": "Hello world!",
    "sound": "default",
    "badge": 1
  },
  "custom":
  {
    "_sfx": {
      "code": 100,
      "data": {
        "targetPlayerId": "<PLAYER_ID>",
        // Some payload
      }
    }
  }
}
----

A typical Android push notification message has the following format:

[source,js]
----
{
  "alert": "Hello world!",
  "custom":
  {
    "_sfx": {
      "code": 100,
      "data": {
        "targetPlayerId": "<PLAYER_ID>",
        // Some payload
      }
    }
  }
}
----

NOTE: The target player id is always included in the data part. As a
security measure, you should always check if the provided target player id
matches your current player and discard the push notification if it is
not the case.

[[guide-push-notifications-reference-automatic-notifications-from-scoreflex-to-players]]
==== Automatic Notifications from Scoreflex to Players

This section describes automatic notifications that can be sent by
Scoreflex.

[[guide-push-notifications-reference-automatic-notifications-from-scoreflex-to-players-challenge-invitation]]
===== Challenge invitation

This push notification is sent when a player is invited by another
player to a challenge.

Code: +100+.

Message: “<NICKNAME> wants to challenge you!”

Payload:

* +inviterId+
* +challengeInstanceId+

[[guide-push-notifications-reference-automatic-notifications-from-scoreflex-to-players-challenge-ended]]
===== Challenge ended

This push notification is sent when a challenge you have taken part in
has ended.

Code: +101+.

Example of messages:

* “You have won a challenge! You have earned 10 points!”
* “You have won a challenge against <NICKNAME>! You have earned 10 points!”
* “You have won a challenge against <NICKNAME> and <NUMBER> others!
   You have earned 10 points!”
* “You have lost a challenge! You have lost 10 points!”
* “You have lost a challenge against <NICKNAME>! You have lost 10 points!”
* “You have lost a challenge against <NICKNAME> and <NUMBER> others!
   You have lost 10 points!”
* “You have achieved a draw!”
* “You have drawn against <NICKNAME>!”
* “You have drawn against <NICKNAME> and <NUMBER> others!”

Payload:

* +challengeInstanceId+

[[guide-push-notifications-reference-automatic-notifications-from-scoreflex-to-players-your-turn-in-challenge]]
===== Your turn in challenge

This push notification is sent when it is the player's turn to play in a
turn-based challenge.

Code: +102+.

Message: "It's your turn to play!"

Payload:

* +challengeInstanceId+

[[guide-push-notifications-reference-automatic-notifications-from-scoreflex-to-players-friend-joined-game]]
===== Friend joined game

This push notification is sent when a friend has joined a game.

Code: +103+.

Message: “Your friend <NICKNAME> just joined <GAME_NAME>!”

Payload:

* +friendId+
* +gameId+

[[guide-push-notifications-reference-automatic-notifications-from-scoreflex-to-players-friend-beat-your-high-score]]
===== Friend beat your high score

This push notification is sent when a friend has beaten one of your high
scores.

Code: +104+.

Message: “<FRIEND_NICKNAME> beat you by <FORMATTED_SCORE_DELTA> on <LEVEL_NAME>!”

Payload:

* +leaderboardId+
* +friendId+
