[[guide-cloud-storage-player-storage-concepts]]
[role="chunk-page chunk-toc"]
==== Concepts

The player storage allows you to store application data for each player
of your game on Scoreflex's servers. Your application can retrieve and
update this user data from any devices using the
http://developer.scoreflex.com/docs/reference/api/v1#StorageService[Storage
Service API]. This service makes it possible to synchronize data for
each player of your game across multiple devices and platforms. For
example, if you have a game that runs on Android, iOS, and the web, you
can use the Storage Service service to allow a user to start a game on
their Android phone, and then continue playing on a tablet, iOS device,
or web browser without losing any of their progress. This service can
also be used to ensure that a user's game play continues from where it
left off even if their device is lost, destroyed, or traded in for a
newer model.

Typical examples of data that can be saved are player's preferences,
progression and everything that should be restore to ensure the best
possible cross-device experience for a player playing on more than one
device. You don't need to use the player storage to maintain your
players' high scores or achievements as these data are automatically
saved and retrievable from dedicated APIs.

Only the player of a game can read and write his own dedicated storage
for a specific game. The player storage is a simple key/value database.

How you represent this data within your application is completely up to
you, but we recommend choosing a platform-independent format so that the
data can easily be read and written from any of the platforms your
application supports. For instance, consider using a platform-neutral
format such as a JSON-encoded string.
