[[guide-games]]
[role="chunk-page chunk-toc"]
== Games

--
--

[[guide-games-concepts]]
=== Concepts

Once you have a developer account, you can begin to integrate Scoreflex
into your games. To do so you have to add your games to Scoreflex. If
your game is already available on the App Store or on Google Play,
Scoreflex can directly fetch the game information for you.

[[guide-games-interact]]
=== Interact

You can use your developer web dashboard and the Management REST API to
set up and manage your games.

[[guide-games-reference]]
=== Reference

A game contains the following fields that can be returned or not by the
API depending on the accessing rights of the caller:

* +id+
* +name+
* +shortDescription+
* +description+
* +website+
* +genres+
* +platforms+
* +version+
* +url+. This is the url of the game's Scoreflex page.

[[guide-games-reference-game-genres]]
==== Game Genres

Here are the game genres supported by Scoreflex:

* +action+
* +adventure+
* +arcade+
* +board+
* +brain & puzzle+
* +card+
* +casino+
* +casual+
* +dice+
* +educational+
* +family+
* +kids+
* +music+
* +racing+
* +role playing+
* +simulation+
* +sports+
* +strategy+
* +trivia+
* +word+
