[[guide-social-networks]]
[role="chunk-page chunk-toc"]
== Social networks

--
--

[[guide-social-networks-authentication]]
=== Authentication

The following social networks are currently supported:

* http://www.facebook.com["Facebook", window="_blank"]
* http://plus.google.com["Google+", window="_blank"]
* http://www.twitter.com["Twitter", window="_blank"]

In order to interact with the Scoreflex API you have first to authenticate your player. You can allow your players
to play and take part to your game competition as a guest. You can also authenticate your players via a social network.

The authentication with social networks can be done inside a webview server side. You can also
use native authentication client-side.

To get more information please refer to the <<guide-authentication,Scoreflex authentication section>>.

[[guide-social-networks-link-multiple-accounts]]
=== Link multiple accounts

[[guide-social-networks-link-multiple-accounts-concepts]]
==== Concepts

In Scoreflex, your players can link their account with multiple social services allowing them to play with their friends
from Google+, Facebook, Twitter and to interact with multiple services at once.

Like for authentication, Scoreflex can handle the linking of a service for you via our webview UI. You can also use native authentication
client-side and link the current player account to a service via the REST API.

[[guide-social-networks-link-multiple-accounts-interact]]
==== Interact

[[guide-social-networks-link-multiple-accounts-interact-link-player-with-service]]
===== Link player with a new social service

[source,sh]
----
$> curl -XPOST 'https://sandbox.api.scoreflex.com/v1/social/links/<SERVICE>'\
'?accessToken=<ACCESS_TOKEN>'\
'&serviceAccessToken=<SERVICE_ACCESS_TOKEN>'
----

[source,js]
----
{
  "success": true
}
----

NOTE: you can only link an already authenticated player to another service.

WARNING: we currently don't support the linking of an already registered account in Scoreflex,
meaning that we don't merge two existing Scoreflex authenticated players.

[[guide-social-networks-link-multiple-accounts-interact-unlink-player-with-service]]
===== Unlink player with a social service

[source,sh]
----
$> curl -XDELETE 'https://sandbox.api.scoreflex.com/v1/social/links/<SERVICE>?accessToken=<ACCESS_TOKEN>'
----

[source,js]
----
{
  "success": true
}
----

NOTE: If the current player is only linked to one service you can't unlink them from this service.


[[guide-social-networks-link-multiple-accounts-reference]]
==== Reference

[[guide-social-networks-link-multiple-accounts-reference-apis]]
===== APIs

http://developer.scoreflex.com/docs/reference/api/v1#post_{empty}_v1_social_links_service[link API reference]
and http://developer.scoreflex.com/docs/reference/api/v1#delete_{empty}_v1_social_links_service[unlink API reference].


[[guide-social-networks-friends-and-contacts]]
=== Friends and contacts

[[guide-social-networks-friends-and-contacts-concepts]]
==== Concepts

When players authenticate to Scoreflex via a social network all their contacts from the social networks are fetched.
In the Scoreflex terminology a player's contact is someone related to the player via a social service that is not
yet registered to Scoreflex.

All imported contacts of a player that are already registered to Scoreflex are automatically added to their Scoreflex
friends. Scoreflex players can manage their friends list by adding or removing friends manually.

In Scoreflex, the friendship relation is asymmetric. Players can add players to their friends list without others
authorization. This can be viewed as a following relationship.

The list of contacts and friends are shared across all games.

[[guide-social-networks-friends-and-contacts-interact]]
==== Interact

[[guide-social-networks-friends-and-contacts-interact-listing-own-friends]]
===== Listing own friends

[source,sh]
----
$> curl -XGET 'https://sandbox.api.scoreflex.com/v1/players/me/friends?accessToken=<ACCESS_TOKEN>'
----

[source,js]
----
{
  "friends": [
    {
      "avatarUrl": "https://www.scoreflex.com/sandbox/avatars/players/0189oiu428700181/",
      "challengeCounters": {
      "1": {
        "lost": 0,
        "played": 1337
        }
      },
      "firstName": "Chuck",
      "friend": true,
      "friends": [
      "018blql3fmd1vu81"
      ],
      "gameSkill": "God",
      "geo": {
        "id": "cYjPGhGBlgP",
        "title": "San Francisco 94133",
        "formatted": "San Francisco 94133, CA, United States",
        "adminLevel": "postalCode",
        "countryCode": "US"
      },
      "id": "0189oiu428700181",
      "language": "en_US",
      "lastName": "Norris",
      "nationality": "US",
      "nickName": "Chuck",
      "serviceIds": {
        "Facebook": "1",
        "Google": "1",
        "Twitter": "1"
      },
      "url": "http://sandbox.api.scoreflex.com/v1/web/players/0189oiu428700181"
   }
  ],
  "friendsCount": 1
}
----

You can use the +filter+ parameter to filter listed friends as follows:

[source,sh]
----
# Returns only the friends that are playing the current game.
# This call can be useful for example to challenge these friends.
$> curl -XGET 'https://sandbox.api.scoreflex.com/v1/players/me/friends?accessToken=<ACCESS_TOKEN>&filter=gamePlayers'
----

[source,sh]
----
# Returns only the friends that are not playing the current game.
# This call can be useful for example to invite these friends to join the game.
$> curl -XGET 'https://sandbox.api.scoreflex.com/v1/players/me/friends?accessToken=<ACCESS_TOKEN>&filter=gameNonPlayers'
----

===== Listing another player friends

[source,sh]
----
$> curl -XGET 'https://sandbox.api.scoreflex.com/v1/players/<PLAYER_ID>/friends?accessToken=<ACCESS_TOKEN>'
----

You can also use the +filter+ parameter to filter listed friends.

===== Listing own contacts

[source,sh]
----
$> curl -XGET 'https://sandbox.api.scoreflex.com/v1/players/me/contacts?accessToken=<ACCESS_TOKEN>'
----

[source,js]
----
{
  "contacts": [
    {
      "avatarUrl": "https://www.scoreflex.com/sandbox/avatars/contacts/327a2f0a69bb9f0502af9cd2faebbfdf/",
      "id": "Facebook:1000012836862302",
      "locale": "fr_FR",
      "name": "Donkey Kong",
      "profile": "https://www.facebook.com/donkeykong",
      "service": "Facebook",
      "serviceId": "1000012836862302"
    },
    {
      "avatarUrl": "https://www.scoreflex.com/sandbox/avatars/contacts/82aea1d7e13dd1b1c93a3bbc43e5e4d3/",
      "description": "person",
      "id": "Google:106189723444098348647",
      "name": "Billy",
      "profile": "https://plus.google.com/+Billy",
      "service": "Google",
      "serviceId": "106189723444098348647"
    },
    {
      "avatarUrl": "https://www.scoreflex.com/sandbox/avatars/contacts/68535c6c237951f4c639808da9a2f8d4/",
      "description": "Cool description",
      "id": "Twitter:1510909501",
      "locale": "en",
      "name": "Steve",
      "profile": "http://twitter.com/Steve",
      "service": "Twitter",
      "serviceId": "1510909501"
    }
  ]
}
----

You can use the +services+ parameter to filter listed contacts as follows:

[source,sh]
----
# Returns only the contacts on Facebook
$> curl -XGET 'https://sandbox.api.scoreflex.com/v1/players/me/contacts?accessToken=<ACCESS_TOKEN>&services=Facebook'
----

[source,sh]
----
# Returns only the contacts on Twitter or Google+
$> curl -XGET 'https://sandbox.api.scoreflex.com/v1/players/me/contacts?accessToken=<ACCESS_TOKEN>&services=Google,Twitter'
----

[[guide-social-networks-friends-and-contacts-reference]]
==== Reference

[[guide-social-networks-friends-and-contacts-reference-friend]]
===== Friend
A player's friend is a player and therefore contains the same fields as any
 player, please
refer to the <<guide-players-reference-player,player reference section>> for more.

[[guide-social-networks-friends-and-contacts-reference-contact]]
===== Contact

A contact contains the following fields that can be returned or not by
the API depending on the context and the accessing rights of the caller:

* +id+
* +name+
* +avatarUrl+
* +locale+
* +profile+
* +service+
* +serviceId+

[[guide-social-networks-friends-and-contacts-reference-apis]]
===== APIs
http://developer.scoreflex.com/docs/reference/api/v1#get_{empty}_v1_players_me_friends[friends API reference]
and http://developer.scoreflex.com/docs/reference/api/v1#get_{empty}_v1_players_me_contacts[contacts API reference].

[[guide-social-networks-invitations]]
=== Invitations

[[guide-social-networks-invitations-concepts]]
==== Concepts

Players can invite their friends and contacts to join them in a game. This is handled automatically by our SDKs
and our default UI components.

You can also decide to handle invitations yourself. To that purpose, invitations APIs (described in the next
section) are available.

[[guide-social-networks-invitations-interact]]
==== Interact

[[guide-social-networks-invitations-interact-marking-contacts-and-friends-as-invited]]
===== Marking some contacts and friends as invited

[source,sh]
----
$> curl -XPOST 'https://sandbox.api.scoreflex.com/v1/social/invitations/018blql3fmd1vu81,Twitter:1510909501,Facebook:1000012836862302?accessToken=<ACCESS_TOKEN>'
----

[source,js]
----
{
  "018blql3fmd1vu81": true,
  "Twitter:1510909501": true,
  "Facebook:1000012836862302": true
}
----

[[guide-social-networks-invitations-interact-getting-contacts-and-friends-invitation-status]]
===== Getting contacts and friends invitation status

[source,sh]
----
$> curl -XGET 'https://sandbox.api.scoreflex.com/v1/social/invitations/018blql3fmd1vu81,Twitter:123,Twitter:1510909501,Facebook:1000012836862302?accessToken=<ACCESS_TOKEN>'
----

[source,js]
----
{
  "018blql3fmd1vu81": true,
  "Twitter:123": false,
  "Twitter:1510909501": true,
  "Facebook:1000012836862302": true
}
----

[[guide-social-networks-invitations-interact-marking-contacts-as-uninvited]]
===== Marking some contacts and friends as uninvited

[source,sh]
----
$> curl -XDELETE 'https://sandbox.api.scoreflex.com/v1/social/invitations/018blql3fmd1vu81,Twitter:1510909501,Facebook:1000012836862302?accessToken=<ACCESS_TOKEN>'
----

[source,js]
----
{
  "success": true
}
----

[[guide-social-networks-invitations-interact-marking-all-contacts-as-uninvited]]
===== Marking all contacts as uninvited

[source,sh]
----
$> curl -XDELETE 'https://sandbox.api.scoreflex.com/v1/social/invitations?accessToken=<ACCESS_TOKEN>'
----

[source,js]
----
{
  "success": true,
}
----

[[guide-social-networks-invitations-interact-reference]]
==== Reference

[[guide-social-networks-invitations-interact-reference-apis]]
===== APIs

http://developer.scoreflex.com/docs/reference/api/v1#post_{empty}_v1_social_invitations_ids[mark as invited API reference], http://developer.scoreflex.com/docs/reference/api/v1#get_{empty}_v1_social_invitations_ids[get invited status API reference], http://developer.scoreflex.com/docs/reference/api/v1#delete_{empty}_v1_social_invitations_ids[delete invited status API reference] and http://developer.scoreflex.com/docs/reference/api/v1#delete_{empty}_v1_social_invitations[reset invited status API reference].

[[guide-social-networks-sharing]]
=== Sharing

_Coming soon._

[[guide-social-networks-virtual-gifts]]
=== Virtual gifts

_Coming soon._
